function curCl = addNucleoplasmIntensityToClusterTable(curCl,plasmInt,channel)
    
    s = size(curCl,1);

    plasmInt = repmat(plasmInt,s,1);

    varsToAdd = {...
    'Mean',...
    'StdDev',...
    'Max',...
    'Min',...
    'Median',...
    'Mode',...
    'Skewness',...
    'Kurtosis',...
    'NumberOfVoxels',...
    'Volume',...
    };

    % exclude variables that are nor present in our table 
    varsToAdd = intersect(varsToAdd,plasmInt.Properties.VariableNames,'stable');
    
    newVarsToAdd = varsToAdd;
    for i=1:numel(varsToAdd)
        newVarsToAdd{i} = ['plasmC',num2str(channel),'_',varsToAdd{i}];
    end

    plasmInt = renamevars(plasmInt,varsToAdd,newVarsToAdd);

    for i=1:numel(newVarsToAdd)
        curCl = addvars(curCl,plasmInt.(newVarsToAdd{i}),...
            'NewVariableNames', newVarsToAdd{i});
    end
end