function cv = getClusterVariablesToKeepInSummaryTable(nc)


clustVars = {'nucUniqueID','eggChamberID','nucID','clustLabel',...
    'clustVoxelCount','clustVolume','clustCentroid_X','clustCentroid_Y','clustCentroid_Z','clustSphericity',...
    'nucVoxelCount','nucVolume',...
    'rootFolder','eggChamberFolder',...
    };
cv = clustVars;

clustChannelVars = {...
    'clustC1_Mean_raw','clustC1_StdDev_raw','clustC1_Median_raw',...
    'clustC1_Mean_plasmCorr','clustC1_StdDev_plasmCorr',...
    'nucC1_Mean_eggChamberCorr','nucC1_Median_eggChamberCorr','clustC1_Median_plasmCorr',...
    'plasmC1_Mean','plasmC1_StdDev''plasmC1_Median',...
    };

for i=1:nc
    cv = [cv, ...
        cellfun(@strrep,clustChannelVars,...
        repmat({'1'},size(clustChannelVars)),...
        repmat({num2str(i)},size(clustChannelVars)),'UniformOutput',0)];
end