function nv = getNucleiVariablesToKeepInSummaryTable(nc)

nucVars = {'nucUniqueID','eggChamberID','nucID','nucVoxelCount',...
    'nucVolume','nClusters','clustMeanVolume','clustStdDevVolume',...
    'clustMeanNumberOfVoxels','clustStdDevNumberOfVoxels',...
    'nucSphericity','nucCentroid_X','nucCentroid_Y','nucCentroid_Z',...
    'plasmNumberOfVoxels','plasmVolume',...
    'rootFolder','eggChamberFolder'};
 
nv = nucVars;

nucChannelVars = {'clustC1_MeanMean_plasmCorr','clustC1_StdDevMean_plasmCorr',...
    'nucC1_Mean_eggChamberCorr','nucC1_Median_eggChamberCorr',...
    'nucC1_Mean_wholeImgCorr','nucC1_Median_wholeImgCorr',...
    'nucC1_Mean_raw','nucC1_StdDev_raw',...
    'plasmC1_Mean_eggChamberCorr','plasmC1_Median_eggChamberCorr',...
    'plasmC1_Mean_wholeImgCorr','plasmC1_Median_wholeImgCorr',...
    'plasmC1_Mean_raw','plasmC1_StdDev_raw','plasmC1_Median_raw',...
    'wholeImgC1_median','eggChamberC1_median',
    };

for i=1:nc
    nv = [nv, ...
        cellfun(@strrep,nucChannelVars,...
        repmat({'1'},size(nucChannelVars)),...
        repmat({num2str(i)},size(nucChannelVars)),'UniformOutput',0)];
end