function nr = addRawIntToTable(ng,intRaw,c,variablePrefix,variableSuffix)
% ng is the table to add intensity to
% intRaw contains the raw intensity data to add
% c is the name of the channel (used to rename variables)
% variablePrefix is a prefix to add to all variable names

% returns nr, the updated table with added variables.

% these variables are inserted in the table before the SurfaceArea variable
varsToAddFirst = {...
    'Mean',...
    'StdDev',...
    'Max',...
    'Min',...
    'Median',...
    'Mode',...
    'Skewness',...
    'Kurtosis',...
    };

% these variables are inserted in the table after the InscrBall_Radius variable
varsToAddLater = {...
    'NumberOfVoxels',...
    'Volume',...
    'NeighborsMean',...
    'NeighborsStdDev',...
    'NeighborsMax',...
    'NeighborsMin',...
    'NeighborsMedian',...
    'NeighborsMode',...
    'NeighborsSkewness',...
    'NeighborsKurtosis',...
    };

% exclude variables that are nor present in our table 
varsToAddFirst = intersect(varsToAddFirst,intRaw.Properties.VariableNames,'stable');
varsToAddLater = intersect(varsToAddLater,intRaw.Properties.VariableNames,'stable');

newVarsToAddFirst = varsToAddFirst;
for i=1:numel(varsToAddFirst)
    newVarsToAddFirst{i} = [variablePrefix,'C',num2str(c),'_',newVarsToAddFirst{i},variableSuffix];
end

newVarsToAddLater = varsToAddLater;
for i=1:numel(varsToAddLater)
    newVarsToAddLater{i} = [variablePrefix,'C',num2str(c),'_',newVarsToAddLater{i},variableSuffix];
end

intRaw = renamevars(intRaw,varsToAddFirst,newVarsToAddFirst);
intRaw = renamevars(intRaw,varsToAddLater,newVarsToAddLater);

nr = ng;
for i=1:numel(newVarsToAddFirst)
    nr = addvars(nr,intRaw.(newVarsToAddFirst{i}),...
        'NewVariableNames', newVarsToAddFirst{i},...
        'Before','rootFolder');
end

for i=1:numel(newVarsToAddLater)
    nr = addvars(nr,intRaw.(newVarsToAddLater{i}),...
        'NewVariableNames', newVarsToAddLater{i});
end


end
